### ISSUE TITLE
Mejor empaquetamiento y distintos sistemas operativos

### ISSUE THREAD

**Issue by benjavicente** [benjavicente/uc-nrc-icalendar#3]
Qt [recomienda][Qt for Python Deployment] usar [fbs], [PyInstaller] o [cv_Freeze] para empaquetar las aplicaciones. Usar pbs requeriría un cambio de licencia a [GPL]. Creo que se necesita empaquetar en los distintos sistemas operativos para obtener el ejecutable correspondiente en cada uno.

Hasta ahora mi proceso de empaquetación simplemente es

```cmd
pyinstaller --name="uc-nrc-icalendar" --windowed --clean --onefile "src/gui.py"
```
la cual produce un ejecutable de 46MB para Windows.

_13-07: Ver [`installer.md`](https://github.com/benjavicente/uc-nrc-icalendar/blob/1c2db8c97c6b331af07406ec09fee0fd32a20b01/installer.md)_

Se podría ver si se puede reducir el tamaño del ejecutable, ver la empaquetación en distintos sistemas operativos (distintas máquinas o virtual) y ver si se puede integrar el empaquetamiento con github actions.

[Qt for Python Deployment]: https://doc.qt.io/qtforpython/deployment.html
[fbs]: https://build-system.fman.io/
[PyInstaller]: https://www.pyinstaller.org/index.html
[cv_Freeze]: https://cx-freeze.readthedocs.io/en/latest/faq.html#freezing-for-other-platforms
[GPL]: https://es.wikipedia.org/wiki/GNU_General_Public_License

**Comment by agucova** [comment]
Pasar a GPL suena razonable la verdad, `fbs` es genial y facilitaría todo. Y lo de empaquetar en cada SO es trivial usando Actions como tu dijiste, ya que tienen VMs con todos los SO importantes. (A mi sorpresa, incluido macOS).

Un `.deb` y un `.dmg` estaría genial, *wink wink*.

**Comment by benjavicente** [comment]
El único problema que tengo con `fbs` es que parece poco configurable en comparación a `PyInstaller` con [spec files](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#). Por ejemplo, me gustaría cambiar la [estructura de los directorios](https://build-system.fman.io/manual/#directory-structure) a algo como

```txt
src
├─── scraper
│    └─── scraper.py
├─── gui
│    ├─── build
│    ├─── assets
│    └─── gui.py
├─── main
│    └─── main.py
└─── schedule
     ├─── constants.py
     └─── schedule.py
```
para ordenar más el directorio, pero no parece existir una opción en la documentación. Voy a tratar de usarlo y comparar los resultados con PyInstaller.

Sobre GitHub actions, tengo [un borrador](https://gist.github.com/benjavicente/5facb9a0657a0c96d4a81200a09ab3d2) que podría funcionar para empaquetar el programa en cada release con PyInstaller. Tiene un problema en el último paso y los paths son de otro repositorio, pero se pueden arreglar fácilmente para que funcione en este.

El cambio de licencia (#8) lo dejaría pendiente por ahora.

**Comment by benjavicente** [comment]
No pude usar `pbs`  para empaquetar el programa :confused:

Pero si pude implementar GitHub Actions con PyInstaller, los ejecutables están en el [artifact del ultimo Action](https://github.com/benjavicente/uc-nrc-icalendar/actions/runs/209103341). Hasta ahora he probado solo el de Windows, que funciona perfecto.

> Un .deb y un .dmg estaría genial

El output de mac y ubuntu no tiene ninguna extensión, puede que falte algo en el spec de PyInstaller :thinking:

**Comment by agucova** [comment]
No tienen extensión porque son ejecutables, no paquetes!

Descomprimí el artifact para Ubuntu y abrió perfecto con la GUI (ícono incluido!) ✨

La verdad es que tal vez es innecesario agregar empaquemiento completo (`.deb`), siendo que es algo que se va a usar una vez por semestre, usarlo como un ejecutable me parece mas que suficiente.

Todavía no he probado con macOS (no puedo ahora mismo), aunque ahí ejecutar cosas directamente en vez de un .app con una firma digital puede ser un poco mas complicado.

**Comment by agucova** [comment]
Un tema que tal vez vale la pena revisar es la compatibilidad con 32bits y otras distros, a lo que tal vez [AppImage](https://appimage.org/) sería la solución, aunque nunca lo he usado con PyInstaller.

De todas formas Ubuntu/Debian y amigos siguen teniendo gran prevalencia, pero supongo que no es taaaan raro encontrar otras distros, especialmente en ingeniería ;)

**UPDATE:** PyInstaller no soporta AppInstaller, eso parece estar contemplado en su modelo de _onefile_, sus ejecutables, después chequeo con otras distros uwu

**Comment by benjavicente** [comment]
Viendo AppImage llegué a [appimage-builder](https://appimage-builder.readthedocs.io/en/latest/), que tiene justo un [ejemplo de como empaquetar python con Qt](https://appimage-builder.readthedocs.io/en/latest/examples/pyqt.html). Se podría usar eso para empaquetar en Linux en vez de PyInstaller y así soportar más distros.

Yo ahora no me manejo mucho con diferentes OS :sweat_smile: . Podría echarle un ojo a eso antes del inicio del próximo semestre.

Aun así, qué soporte Windows y MacOS ~está~ estaría  perfecto :tada:
